name: Checks
on: [push]
jobs:
  ci:
    name: Lint using rome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependencies
        run: npm ci
      - name: Lint rome
        run: npx rome ci .
